### ISSUE TITLE
Roadmap to version 1.0

### ISSUE THREAD

**Issue by ismyrnow** [knownasilya/just-auth#8]
This issue is to discuss the roadmap for Version 1.0. I will try to lay out my understanding of what functionality will be in 1.0, and discussion will drive the final state of the roadmap shown below. This will also link to individual issues once we have some consensus about their existence.

### Version 1.0 Roadmap

- [x] **JSON Web Tokens** (Issue ?)
- [x] **Authentication middleware** (Issue #7)
- [x] **Authentication routes**
- [ ] **~~Basic Auth support~~** (edited by @knownasilya)
- [ ] **Ember Simple Auth support** (Issue #9 )
- [ ] ?

**Comment by ismyrnow** [comment]
I like how this project handles multiple authentication strategies: https://github.com/izaakschroeder/express-authentication

They let you define different pieces of auth middlware, then wrap up each strategy in a single call to `auth.required()`.

I would primarily be interested in providing default middleware for JWT and Basic Auth, along with the existing router. Could v1.0 wrap that module with default strategies, and expose the same simple interface (getUser, etc.)?

**Comment by ismyrnow** [comment]
I'd be fine if this module was opinionated and didn't provide extensible auth strategies, but just supported a few different ones. I'd rather have a trivial to implement module than a do-it-all module, since the goal is to use this widely across our many SPA apps.

**Comment by calvinmetcalf** [comment]
published https://www.npmjs.com/package/pbkdf2-utils for using the built in pbkdf2

**Comment by calvinmetcalf** [comment]
I implemented token auth for sccog without this, some notes about making this more useful for using with an app like that

The flow for json web token apps is different for traditional apps because you can not (easily) revoke them once they are given out. (you can set up a system for invalidating them, but that means you need to check a database to make sure the token hasn't been invalidated at which point why don't you just store all the info in the database). Instead the flow is that you set an expression date for the token and the app periodically refreshes its, so we need a route for getting the token and one for refreshing the token but we don't need one for logging out because to 'log out' all you really do is on the client side forget the token.

Additionally the getUser callback is the only one that really matters on the server side because you can only invalidate or update a user when their token expires, e.g. update user in the database and then next time they refresh they get the update.  The client can refresh early but that is something only applies to well behaved clients so shouldn't be relied upon by the server.

**Comment by knownasilya** [comment]
@calvinmetcalf I think `updateUser` is still handy, but optional. Since you could use that to add additional data to the token before it's generated. Maybe a rename is in order.

**Comment by calvinmetcalf** [comment]
2 things occurred to me, the keep me signed in issue could be solved by having a refresh only token by setting the subject to 'refresh', we could also do the reverse and have a subject for access that if omitted would make it a refresh only token.  As this isn't really standard we'd have to make our own fork of the ember web token plugin to enable this 

much l like you can quickly invalidate all traditional opaque tokens by flushing redis, you could have the same effect by creating a new secret you use to sign the key. If they are randomly generated then simply refreshing the server would do it, for scaling environments we'd have to come up with a better way to do it (maybe with pub sub?) but the principal would remain the same.

**Comment by knownasilya** [comment]
@calvinmetcalf how should we be using pbkdf2-utils?

**Comment by knownasilya** [comment]
Closing this in favor of sub issues.
